version: '3.4'

services:
  notas.server:
    image: ${DOCKER_REGISTRY-}notasserver
    build:
      context: .
      dockerfile: Notas.Server/Dockerfile
    depends_on: 
            - databaseNotas
  databaseNotas:
    image: mcr.microsoft.com/mssql/server:2017-latest
    container_name: SqlServerNotas
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "!1PasswordBackEnd."
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
    hostname: backdb-container

  usuarios.server:
    image: ${DOCKER_REGISTRY-}usuariosserver
    build:
      context: .
      dockerfile: Usuarios.Server/Dockerfile
    depends_on: 
            - databaseUsuarios
  databaseUsuarios:
    image: mcr.microsoft.com/mssql/server:2017-latest
    container_name: SqlServerUsuarios
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "!1PasswordBackEnd."
      MSSQL_PID: "Developer"
    ports:
      - "1445:1444"
    hostname: backdb-container-2

