// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Notas.Server.Models;

#nullable disable

namespace Notas.Server.Migrations
{
    [DbContext(typeof(MiDbContext))]
    [Migration("20240416180606_Notas")]
    partial class Notas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Notas.Server.Models.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Categorias");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Sin categoria"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Ejercicio"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Diario"
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "Recetas"
                        },
                        new
                        {
                            Id = 5,
                            Nombre = "Pendientes"
                        },
                        new
                        {
                            Id = 6,
                            Nombre = "Compras pendientes"
                        },
                        new
                        {
                            Id = 7,
                            Nombre = "Comandos .Net"
                        });
                });

            modelBuilder.Entity("Notas.Server.Models.Nota", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdCategoria")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("IdCategoria");

                    b.ToTable("Notas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Hoy me senti muy bien fui por helado y luego comi pizza",
                            Fecha = new DateTime(2024, 4, 16, 13, 6, 5, 231, DateTimeKind.Local).AddTicks(2288),
                            IdCategoria = 3,
                            Titulo = "Dia 16"
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Realizar 5 repeticiones con 40 segundos de descanso entre repeticiones",
                            Fecha = new DateTime(2024, 4, 16, 13, 6, 5, 231, DateTimeKind.Local).AddTicks(2323),
                            IdCategoria = 2,
                            Titulo = "Palanca"
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = "Hacer 45 repeticiones minimo diario sobre la barra",
                            Fecha = new DateTime(2024, 4, 16, 13, 6, 5, 231, DateTimeKind.Local).AddTicks(2343),
                            IdCategoria = 2,
                            Titulo = "Barra"
                        },
                        new
                        {
                            Id = 4,
                            Descripcion = "Pollo, panco, aceite, pimienta, chipotle, salsa de ajo, perejil",
                            Fecha = new DateTime(2024, 4, 16, 13, 6, 5, 231, DateTimeKind.Local).AddTicks(2362),
                            IdCategoria = 4,
                            Titulo = "Milanesa"
                        },
                        new
                        {
                            Id = 5,
                            Descripcion = "Pastas, Pollo, crema de champiñones, pimenton, cebolla, pimienta, salsa, leche y crema de leche",
                            Fecha = new DateTime(2024, 4, 16, 13, 6, 5, 231, DateTimeKind.Local).AddTicks(2381),
                            IdCategoria = 4,
                            Titulo = "Pastas en salsa de champiñones"
                        },
                        new
                        {
                            Id = 6,
                            Descripcion = "Arina, levadura, pasta de tomate",
                            Fecha = new DateTime(2024, 4, 16, 13, 6, 5, 231, DateTimeKind.Local).AddTicks(2403),
                            IdCategoria = 4,
                            Titulo = "Masa de pizza"
                        },
                        new
                        {
                            Id = 7,
                            Descripcion = "add-migration (nombredelamigracion; update-database;)",
                            Fecha = new DateTime(2024, 4, 16, 13, 6, 5, 231, DateTimeKind.Local).AddTicks(2422),
                            IdCategoria = 7,
                            Titulo = "Migrar BD"
                        });
                });

            modelBuilder.Entity("Notas.Server.Models.Nota", b =>
                {
                    b.HasOne("Notas.Server.Models.Categoria", "Categoria")
                        .WithMany("Notas")
                        .HasForeignKey("IdCategoria")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("Notas.Server.Models.Categoria", b =>
                {
                    b.Navigation("Notas");
                });
#pragma warning restore 612, 618
        }
    }
}
